package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.remoteParameters.customHashiCorpVaultParameter
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        expect {
            customHashiCorpVaultParameter {
                name = "CUSTOM_DOCKER_PASSWORD"
            }
        }
        update {
            customHashiCorpVaultParameter {
                name = "CUSTOM_DOCKER_PASSWORD"
                vaultQuery = "teamcity-custom-plugin-vault"
            }
        }
    }
}
