package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.HashiCorpVaultConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.hashiCorpVaultConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        remove {
            remote("RemoteParameter",
                   remoteType = "RemoteParameterType",
                   params = arrayOf(
                       "property" to "value"
                   )
            )
        }
    }

    features {
        val feature1 = find<HashiCorpVaultConnection> {
            hashiCorpVaultConnection {
                id = "PROJECT_EXT_8"
                name = "HashiCorp Vault Local Approle"
                namespace = "approle"
                url = "https://vault.burnasheva.click:8200"
                authMethod = appRole {
                    roleId = "e0d9ef3e-a837-c70c-ea96-46e9870e6567"
                    secretId = "credentialsJSON:7b85af73-566a-40d4-a6e6-1b7cb4ab7154"
                }
            }
        }
        feature1.apply {
            authMethod = appRole {
                endpointPath = "approle"
                roleId = "7c132444-a5c7-532e-4efe-a46e7104c560"
                secretId = "credentialsJSON:e8cd7d12-4c3d-4b8d-9753-6db7ce4f2079"
            }
            param("teamcity.vault.requirement", "")
        }
    }
}
